use the mockery version 0.9.3 as version 0.9.4 requires hamcrest/hamcrest-php 1.2.2 and this is causing the following error while testing:
Fatal error: Cannot redeclare any() (previously declared in /Users/mz/Codes/Projects/PHP-Packages/cdn/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:395) in /Users/mz/Codes/Projects/PHP-Packages/cdn/vendor/ph
punit/phpunit/src/Framework/Assert/Functions.php on line 59